import type { Metadata } from "next";
import { Suspense } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import ReactQueryProvider from "@/providers/QueryClientProvider";
import Header from "../components/Header";
import Loading from "../components/Loading";
import { createClient } from "@/lib/supabase/server";
import { dehydrate, HydrationBoundary, QueryClient } from "@tanstack/react-query";
import getMyInfo from "../api/profiles/me/getMyInfo";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  const supabase = await createClient();

  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    redirect("/login");
  }

  await queryClient.prefetchQuery({
    queryKey: ["myProfile"],
    queryFn: async () => {
      const info = await getMyInfo(supabase, user.id);
      if (!info) throw new Error("not found");
      return info;
    },
  });

  return (
    <html lang="ja">
      <ReactQueryProvider>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <Suspense fallback={<Loading />}>
              <Header />
            </Suspense>
            {children}
          </HydrationBoundary>
        </body>
      </ReactQueryProvider>
    </html>
  );
}
